### ISSUE TITLE
Mochi support?

### ISSUE THREAD

**Issue by jepjoo** [Vchitect/FasterCache#2]
Hiya,

Do you plan to support Mochi?

Nice results btw, video models really need optimizations for faster generation.

**Comment by cszy98** [comment]
Thank you for your interest. We will soon attempt to implement FasterCache on Mochi.

**Comment by kijai** [comment]
I have an initial working implementation for mochi on a separate branch here for now:

https://github.com/kijai/ComfyUI-MochiWrapper/tree/fastercache

Still unsure if it's fully right and how to use it, it only works if you adjust the sigma schedule (less linear steps), otherwise it destroys the quality.

https://github.com/user-attachments/assets/b15c36b9-a556-4d2f-ad39-27cdbfad17c8

**Comment by cszy98** [comment]
Hi, we have implemented the script for Mochi. Thank you for your interest.
